use crate::types::{Difficulty, TimingBaseline};

/// The 16 default baselines (4 challenge types x 4 difficulties).
pub fn default_baselines() -> Vec<TimingBaseline> {
    vec![
        // crypto-nl
        TimingBaseline {
            challenge_type: "crypto-nl".into(),
            difficulty: Difficulty::Easy,
            mean_ms: 150.0,
            std_ms: 60.0,
            too_fast_ms: 20.0,
            ai_lower_ms: 40.0,
            ai_upper_ms: 1000.0,
            human_ms: 8000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "crypto-nl".into(),
            difficulty: Difficulty::Medium,
            mean_ms: 300.0,
            std_ms: 120.0,
            too_fast_ms: 30.0,
            ai_lower_ms: 50.0,
            ai_upper_ms: 2000.0,
            human_ms: 10000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "crypto-nl".into(),
            difficulty: Difficulty::Hard,
            mean_ms: 600.0,
            std_ms: 200.0,
            too_fast_ms: 50.0,
            ai_lower_ms: 100.0,
            ai_upper_ms: 3000.0,
            human_ms: 15000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "crypto-nl".into(),
            difficulty: Difficulty::Adversarial,
            mean_ms: 1000.0,
            std_ms: 350.0,
            too_fast_ms: 80.0,
            ai_lower_ms: 150.0,
            ai_upper_ms: 5000.0,
            human_ms: 20000.0,
            timeout_ms: 30000.0,
        },
        // multi-step
        TimingBaseline {
            challenge_type: "multi-step".into(),
            difficulty: Difficulty::Easy,
            mean_ms: 400.0,
            std_ms: 150.0,
            too_fast_ms: 40.0,
            ai_lower_ms: 80.0,
            ai_upper_ms: 2000.0,
            human_ms: 12000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "multi-step".into(),
            difficulty: Difficulty::Medium,
            mean_ms: 800.0,
            std_ms: 300.0,
            too_fast_ms: 60.0,
            ai_lower_ms: 150.0,
            ai_upper_ms: 4000.0,
            human_ms: 15000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "multi-step".into(),
            difficulty: Difficulty::Hard,
            mean_ms: 1200.0,
            std_ms: 400.0,
            too_fast_ms: 100.0,
            ai_lower_ms: 300.0,
            ai_upper_ms: 5000.0,
            human_ms: 20000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "multi-step".into(),
            difficulty: Difficulty::Adversarial,
            mean_ms: 1800.0,
            std_ms: 500.0,
            too_fast_ms: 150.0,
            ai_lower_ms: 400.0,
            ai_upper_ms: 7000.0,
            human_ms: 25000.0,
            timeout_ms: 30000.0,
        },
        // ambiguous-logic
        TimingBaseline {
            challenge_type: "ambiguous-logic".into(),
            difficulty: Difficulty::Easy,
            mean_ms: 200.0,
            std_ms: 80.0,
            too_fast_ms: 20.0,
            ai_lower_ms: 50.0,
            ai_upper_ms: 1500.0,
            human_ms: 10000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "ambiguous-logic".into(),
            difficulty: Difficulty::Medium,
            mean_ms: 400.0,
            std_ms: 150.0,
            too_fast_ms: 40.0,
            ai_lower_ms: 80.0,
            ai_upper_ms: 2500.0,
            human_ms: 12000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "ambiguous-logic".into(),
            difficulty: Difficulty::Hard,
            mean_ms: 700.0,
            std_ms: 250.0,
            too_fast_ms: 60.0,
            ai_lower_ms: 120.0,
            ai_upper_ms: 3500.0,
            human_ms: 15000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "ambiguous-logic".into(),
            difficulty: Difficulty::Adversarial,
            mean_ms: 1000.0,
            std_ms: 350.0,
            too_fast_ms: 80.0,
            ai_lower_ms: 200.0,
            ai_upper_ms: 5000.0,
            human_ms: 20000.0,
            timeout_ms: 30000.0,
        },
        // code-execution
        TimingBaseline {
            challenge_type: "code-execution".into(),
            difficulty: Difficulty::Easy,
            mean_ms: 300.0,
            std_ms: 100.0,
            too_fast_ms: 30.0,
            ai_lower_ms: 60.0,
            ai_upper_ms: 1500.0,
            human_ms: 15000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "code-execution".into(),
            difficulty: Difficulty::Medium,
            mean_ms: 500.0,
            std_ms: 200.0,
            too_fast_ms: 50.0,
            ai_lower_ms: 100.0,
            ai_upper_ms: 3000.0,
            human_ms: 20000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "code-execution".into(),
            difficulty: Difficulty::Hard,
            mean_ms: 900.0,
            std_ms: 300.0,
            too_fast_ms: 80.0,
            ai_lower_ms: 150.0,
            ai_upper_ms: 4500.0,
            human_ms: 25000.0,
            timeout_ms: 30000.0,
        },
        TimingBaseline {
            challenge_type: "code-execution".into(),
            difficulty: Difficulty::Adversarial,
            mean_ms: 1500.0,
            std_ms: 450.0,
            too_fast_ms: 120.0,
            ai_lower_ms: 250.0,
            ai_upper_ms: 6000.0,
            human_ms: 30000.0,
            timeout_ms: 30000.0,
        },
    ]
}

/// Look up a baseline by challenge type and difficulty.
pub fn get_baseline<'a>(
    baselines: &'a [TimingBaseline],
    challenge_type: &str,
    difficulty: &Difficulty,
) -> Option<&'a TimingBaseline> {
    baselines
        .iter()
        .find(|b| b.challenge_type == challenge_type && b.difficulty == *difficulty)
}
